version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: les-delices-de-tressy-proxy
    ports:
      - '90:90'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      target: production-build-stage
      dockerfile: Dockerfile
    container_name: les-delices-de-tressy-server
    ports:
      - '61155:61155'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mvertes/alpine-mongo
    container_name: les-delices-de-tressy-mongo
    ports:
      - '27018:27018'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
