# baseURL
@baseURL = http://localhost:61155/api/auth

###
# User Signup
POST {{ baseURL }}/sign-up
Content-Type: application/json

{
    "email": "fabrice@email.com",
    "password": "password"
}

###
# User Login
POST {{ baseURL }}/sign-in
Content-Type: application/json

{
    "email": "fabrice@email.com",
    "password": "password"
}

###
# User Logout
POST {{ baseURL }}/sign-out
Content-Type: application/json
